<p style="padding:8px;background-color:Orange;color:White;font-family:newtimeroman;font-weight: bold;text-align:center;font-size:28px;"> 👤 CUSTOMER CHURN ↓ PREDICTION 📈</p>

In [1]:
#Importing libraries
import pandas as pd
import numpy as np  
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots 
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn import metrics
from sklearn.metrics import recall_score, confusion_matrix, precision_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score, accuracy_score, classification_report
from sklearn.metrics import*

# Dataset Import

In [2]:
df = pd.read_csv(f'D:\Projects DA\Customer_Churn\CustomerData.csv')

In [3]:
df.head()

,Customer_ID,Gender,Age,Married,State,Number_of_Referrals,Tenure_in_Months,Value_Deal,Phone_Service,Multiple_Lines,...,Payment_Method,Monthly_Charge,Total_Charges,Total_Refunds,Total_Extra_Data_Charges,Total_Long_Distance_Charges,Total_Revenue,Customer_Status,Churn_Category,Churn_Reason
0,221958-KAR,Female,33,Yes,Delhi,3,10,Deal 2,Yes,No,...,Bank Withdrawal,50.904325,509.043247,0.00,0,98.43,607.473247,Stayed,NaN,NaN
1,231932-RAJ,Female,53,No,Punjab,0,46,Deal 4,Yes,No,...,Mailed Check,67.358596,3098.495418,0.00,0,395.85,3494.345418,Stayed,NaN,NaN
2,210268-TAM,Female,54,Yes,West Bengal,5,50,Deal 5,Yes,Yes,...,Bank Withdrawal,51.935517,2596.775841,0.00,0,410.52,3007.295841,Stayed,NaN,NaN
3,154886-KER,Female,84,Yes,Delhi,10,3,Deal 1,Yes,Yes,...,Bank Withdrawal,84.530693,253.592080,0.00,0,129.04,382.632080,Joined,NaN,NaN
4,621430-RAJ,Female,42,Yes,Delhi,3,39,Deal 3,Yes,No,...,Bank Withdrawal,54.462510,2124.037906,38.07,0,392.76,2478.727906,Stayed,NaN,NaN

<span style="padding: 8px; font-family:Georgia;font-weight:bold;color:black; font-size:28px;"> Interpreting the Dataset</span>
<a id = "Undertanding the data" ></a>

In [4]:
df.columns

Index(['Customer_ID', 'Gender', 'Age', 'Married', 'State',
       'Number_of_Referrals', 'Tenure_in_Months', 'Value_Deal',
       'Phone_Service', 'Multiple_Lines', 'Internet_Service', 'Internet_Type',
       'Online_Security', 'Online_Backup', 'Device_Protection_Plan',
       'Premium_Support', 'Streaming_TV', 'Streaming_Movies',
       'Streaming_Music', 'Unlimited_Data', 'Contract', 'Paperless_Billing',
       'Payment_Method', 'Monthly_Charge', 'Total_Charges', 'Total_Refunds',
       'Total_Extra_Data_Charges', 'Total_Long_Distance_Charges',
       'Total_Revenue', 'Customer_Status', 'Churn_Category', 'Churn_Reason'],
      dtype='object')

In [5]:
df['Customer_Status'].unique()

array(['Stayed', 'Joined', 'Churned'], dtype=object)

**In this Telecom Company Dataset, we have:**

● **Churn Information**
- 'Customer_Status' (Target Variable)
- 'Churn_Category', 'Churn_Reason' (Post-churn insights)

● **Services Provided**
- 'Phone_Service', 'Multiple_Lines', 'Internet_Service', 'Internet_Type',
  'Online_Security', 'Online_Backup', 'Device_Protection_Plan',
  'Premium_Support', 'Streaming_TV', 'Streaming_Movies',
  'Streaming_Music', 'Unlimited_Data'

● **Billing & Financial Features**
- 'Monthly_Charge', 'Total_Charges', 'Total_Refunds',
  'Total_Extra_Data_Charges', 'Total_Long_Distance_Charges',
  'Total_Revenue'

● **Account & Contract Information**
- 'Contract', 'Paperless_Billing', 'Payment_Method'

● **Customer Behavior**
- 'Tenure_in_Months', 'Number_of_Referrals', 'Value_Deal'

● **Demographics**
- 'Gender', 'Age', 'Married', 'State'

In [6]:
df.shape

(99995, 32)

# Data Cleaning

In [7]:
#Checking duplicates

dup_values = df.duplicated('Customer_ID').sum()
dup_values

np.int64(554)

In [8]:
#Drop duplicates

df = df.drop_duplicates(subset='Customer_ID', keep=False)

In [9]:
df.duplicated('Customer_ID').sum()

np.int64(0)

In [10]:
df.shape

(98887, 32)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 98887 entries, 0 to 99994
Data columns (total 32 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Customer_ID                  98887 non-null  object
 1   Gender                       98887 non-null  object
 2   Age                          98887 non-null  int64
 3   Married                      98887 non-null  object
 4   State                        98887 non-null  object
 5   Number_of_Referrals          98887 non-null  int64
 6   Tenure_in_Months             98887 non-null  int64
 7   Value_Deal                   82443 non-null  object
 8   Phone_Service                98887 non-null  object
 9   Multiple_Lines               98887 non-null  object
 10  Internet_Service             98887 non-null  object
 11  Internet_Type                98887 non-null  object
 12  Online_Security              98887 non-null  object
 13  Online_Backup                98887 non-null  object
 14  Device_Protection_Plan       98887 non-null  object
 15  Premium_Support              98887 non-null  object
 16  Streaming_TV                 98887 non-null  object
 17  Streaming_Movies             98887 non-null  object
 18  Streaming_Music              98887 non-null  object
 19  Unlimited_Data               98887 non-null  object
 20  Contract                     98887 non-null  object
 21  Paperless_Billing            98887 non-null  object
 22  Payment_Method               98887 non-null  object
 23  Monthly_Charge               98887 non-null  float64
 24  Total_Charges                98887 non-null  float64
 25  Total_Refunds                98887 non-null  float64
 26  Total_Extra_Data_Charges     98887 non-null  int64
 27  Total_Long_Distance_Charges  98887 non-null  float64
 28  Total_Revenue                98887 non-null  float64
 29  Customer_Status              98887 non-null  object
 30  Churn_Category               17225 non-null  object
 31  Churn_Reason                 17225 non-null  object
dtypes: float64(5), int64(4), object(23)
memory usage: 24.9+ MB

In [12]:
#Checking Null Values

df.isnull().sum()

Customer_ID                        0
Gender                             0
Age                                0
Married                            0
State                              0
Number_of_Referrals                0
Tenure_in_Months                   0
Value_Deal                     16444
Phone_Service                      0
Multiple_Lines                     0
Internet_Service                   0
Internet_Type                      0
Online_Security                    0
Online_Backup                      0
Device_Protection_Plan             0
Premium_Support                    0
Streaming_TV                       0
Streaming_Movies                   0
Streaming_Music                    0
Unlimited_Data                     0
Contract                           0
Paperless_Billing                  0
Payment_Method                     0
Monthly_Charge                     0
Total_Charges                      0
Total_Refunds                      0
Total_Extra_Data_Charges           0
Total_Long_Distance_Charges        0
Total_Revenue                      0
Customer_Status                    0
Churn_Category                 81662
Churn_Reason                   81662
dtype: int64

In [13]:
df['Customer_Status'].value_counts()

Customer_Status
Stayed     71835
Churned    17225
Joined      9827
Name: count, dtype: int64

# SQL use in python

In [14]:
import sqlite3 
conn = sqlite3.connect("C:\\Users\\ddade\\Documents\\df.db") #create database

In [15]:
df.to_sql('churn', conn, index=False, if_exists='replace')  #create table

98887

In [16]:
query = """
SELECT Gender, COUNT(*) as total
FROM churn
GROUP BY Gender
"""
result = pd.read_sql_query(query, conn)
print(result)

   Gender  total
0  Female  59465
1    Male  39422

In [17]:
pd.read_sql_query("""
SELECT Gender, COUNT(*) as total
FROM churn
GROUP BY Gender
""",conn)

   Gender  total
0  Female  59465
1    Male  39422

In [18]:
pd.read_sql_query("""
SELECT 
    Gender, 
    COUNT(*) as TotalCount,
    COUNT(*) * 100.0 / (SELECT COUNT(*) FROM churn) as Percentage 
FROM churn
GROUP BY Gender
""", conn)

   Gender  TotalCount  Percentage
0  Female       59465   60.134295
1    Male       39422   39.865705

In [19]:
pd.read_sql_query("""Select Contract, Count(Contract) 
AS Total,
Count (Contract) * 100.0 / (Select Count (*) from churn) AS percentage
From churn
Group by Contract""",conn)

         Contract  Total  percentage
0  Month-to-Month  39892   40.340995
1        One Year  26653   26.952987
2        Two Year  32342   32.706018

In [20]:
pd.read_sql_query("""Select Customer_Status,Count(Customer_Status) AS Total,
SUM(Total_Revenue) AS TotalRevenue,
SUM(Total_Revenue) / (Select SUM(Total_Revenue) from churn) * 100 AS RevenuePercentage
from churn
Group by Customer_Status""",conn)

  Customer_Status  Total  TotalRevenue  RevenuePercentage
0         Churned  17225  2.658053e+07          11.795150
1          Joined   9827  3.695708e+06           1.639976
2          Stayed  71835  1.950751e+08          86.564873

In [21]:
df['Total_Revenue'].describe()

count    98887.000000
mean      2278.876958
std       1515.127142
min          5.944825
25%       1118.044854
50%       2045.316767
75%       3193.379443
max       9107.550000
Name: Total_Revenue, dtype: float64

In [22]:
pd.options.display.float_format='{:,.2f}'.format

In [ ]:
pd.read_sql_query("""Select Customer_Status,Count(Customer_Status) AS Total,
Round(SUM(Total_Revenue),2) AS TotalRevenue,
SUM(Total_Revenue) / (Select SUM(Total_Revenue) from churn) * 100 AS RevenuePercentage
from churn
Group by Customer_Status""",conn)

  Customer_Status  Total   TotalRevenue  RevenuePercentage
0         Churned  17225  26,580,525.31              11.80
1          Joined   9827   3,695,707.82               1.64
2          Stayed  71835 195,075,072.67              86.56

In [24]:
pd.read_sql_query("""SELECT State,
Round(Count(State),2)*100 / (Select Count(*) from churn) AS Percentage from churn
Group By State
Order By Percentage Desc""",conn)

           State  Percentage
0          Delhi       29.47
1      Rajasthan       12.81
2        Gujarat       11.82
3         Kerala       10.20
4         Punjab        9.74
5    West Bengal        8.70
6      Karnataka        8.60
7     Tamil Nadu        3.33
8    Maharashtra        3.25
9  Uttar Pradesh        2.07

In [25]:
#Count NULL Values by Using SQL Query

pd.read_sql_query("""SELECT 
    SUM(CASE WHEN Customer_ID IS NULL THEN 1 ELSE 0 END) AS Customer_ID_Null_Count,
    SUM(CASE WHEN Gender IS NULL THEN 1 ELSE 0 END) AS Gender_Null_Count,
    SUM(CASE WHEN Age IS NULL THEN 1 ELSE 0 END) AS Age_Null_Count,
    SUM(CASE WHEN Married IS NULL THEN 1 ELSE 0 END) AS Married_Null_Count,
    SUM(CASE WHEN State IS NULL THEN 1 ELSE 0 END) AS State_Null_Count,
    SUM(CASE WHEN Number_of_Referrals IS NULL THEN 1 ELSE 0 END) AS Number_of_Referrals_Null_Count,
    SUM(CASE WHEN Tenure_in_Months IS NULL THEN 1 ELSE 0 END) AS Tenure_in_Months_Null_Count,
    SUM(CASE WHEN Value_Deal IS NULL THEN 1 ELSE 0 END) AS Value_Deal_Null_Count,
    SUM(CASE WHEN Phone_Service IS NULL THEN 1 ELSE 0 END) AS Phone_Service_Null_Count,
    SUM(CASE WHEN Multiple_Lines IS NULL THEN 1 ELSE 0 END) AS Multiple_Lines_Null_Count,
    SUM(CASE WHEN Internet_Service IS NULL THEN 1 ELSE 0 END) AS Internet_Service_Null_Count,
    SUM(CASE WHEN Internet_Type IS NULL THEN 1 ELSE 0 END) AS Internet_Type_Null_Count,
    SUM(CASE WHEN Online_Security IS NULL THEN 1 ELSE 0 END) AS Online_Security_Null_Count,
    SUM(CASE WHEN Online_Backup IS NULL THEN 1 ELSE 0 END) AS Online_Backup_Null_Count,
    SUM(CASE WHEN Device_Protection_Plan IS NULL THEN 1 ELSE 0 END) AS Device_Protection_Plan_Null_Count,
    SUM(CASE WHEN Premium_Support IS NULL THEN 1 ELSE 0 END) AS Premium_Support_Null_Count,
    SUM(CASE WHEN Streaming_TV IS NULL THEN 1 ELSE 0 END) AS Streaming_TV_Null_Count,
    SUM(CASE WHEN Streaming_Movies IS NULL THEN 1 ELSE 0 END) AS Streaming_Movies_Null_Count,
    SUM(CASE WHEN Streaming_Music IS NULL THEN 1 ELSE 0 END) AS Streaming_Music_Null_Count,
    SUM(CASE WHEN Unlimited_Data IS NULL THEN 1 ELSE 0 END) AS Unlimited_Data_Null_Count,
    SUM(CASE WHEN Contract IS NULL THEN 1 ELSE 0 END) AS Contract_Null_Count,
    SUM(CASE WHEN Paperless_Billing IS NULL THEN 1 ELSE 0 END) AS Paperless_Billing_Null_Count,
    SUM(CASE WHEN Payment_Method IS NULL THEN 1 ELSE 0 END) AS Payment_Method_Null_Count,
    SUM(CASE WHEN Monthly_Charge IS NULL THEN 1 ELSE 0 END) AS Monthly_Charge_Null_Count,
    SUM(CASE WHEN Total_Charges IS NULL THEN 1 ELSE 0 END) AS Total_Charges_Null_Count,
    SUM(CASE WHEN Total_Refunds IS NULL THEN 1 ELSE 0 END) AS Total_Refunds_Null_Count,
    SUM(CASE WHEN Total_Extra_Data_Charges IS NULL THEN 1 ELSE 0 END) AS Total_Extra_Data_Charges_Null_Count,
    SUM(CASE WHEN Total_Long_Distance_Charges IS NULL THEN 1 ELSE 0 END) AS Total_Long_Distance_Charges_Null_Count,
    SUM(CASE WHEN Total_Revenue IS NULL THEN 1 ELSE 0 END) AS Total_Revenue_Null_Count,
    SUM(CASE WHEN Customer_Status IS NULL THEN 1 ELSE 0 END) AS Customer_Status_Null_Count,
    SUM(CASE WHEN Churn_Category IS NULL THEN 1 ELSE 0 END) AS Churn_Category_Null_Count,
    SUM(CASE WHEN Churn_Reason IS NULL THEN 1 ELSE 0 END) AS Churn_Reason_Null_Count
FROM churn""",conn)

,Customer_ID_Null_Count,Gender_Null_Count,Age_Null_Count,Married_Null_Count,State_Null_Count,Number_of_Referrals_Null_Count,Tenure_in_Months_Null_Count,Value_Deal_Null_Count,Phone_Service_Null_Count,Multiple_Lines_Null_Count,...,Payment_Method_Null_Count,Monthly_Charge_Null_Count,Total_Charges_Null_Count,Total_Refunds_Null_Count,Total_Extra_Data_Charges_Null_Count,Total_Long_Distance_Charges_Null_Count,Total_Revenue_Null_Count,Customer_Status_Null_Count,Churn_Category_Null_Count,Churn_Reason_Null_Count
0,0,0,0,0,0,0,0,16444,0,0,...,0,0,0,0,0,0,0,0,81662,81662

In [26]:
#Remove null and insert the new data into Prod table

conn.execute("""
CREATE TABLE prod_Churn AS
SELECT
    Customer_ID,
    Gender,
    Age,
    Married,
    State,
    Number_of_Referrals,
    Tenure_in_Months,
    IFNULL(Value_Deal, 'None') AS Value_Deal,
    Phone_Service,
    IFNULL(Multiple_Lines, 'No') As Multiple_Lines,
    Internet_Service,
    IFNULL(Internet_Type, 'None') AS Internet_Type,
    IFNULL(Online_Security, 'No') AS Online_Security,
    IFNULL(Online_Backup, 'No') AS Online_Backup,
    IFNULL(Device_Protection_Plan, 'No') AS Device_Protection_Plan,
    IFNULL(Premium_Support, 'No') AS Premium_Support,
    IFNULL(Streaming_TV, 'No') AS Streaming_TV,
    IFNULL(Streaming_Movies, 'No') AS Streaming_Movies,
    IFNULL(Streaming_Music, 'No') AS Streaming_Music,
    IFNULL(Unlimited_Data, 'No') AS Unlimited_Data,
    Contract,
    Paperless_Billing,
    Payment_Method,
    Monthly_Charge,
    Total_Charges,
    Total_Refunds,
    Total_Extra_Data_Charges,
    Total_Long_Distance_Charges,
    Total_Revenue,
    Customer_Status,
    IFNULL(Churn_Category, 'Others') AS Churn_Category,
    IFNULL(Churn_Reason , 'Others') AS Churn_Reason
    FROM churn""")

In [47]:
prod_ChurnImport = pd.read_sql_query("Select * from prod_Churn",conn)

In [48]:
prod_ChurnImport.to_excel('prod_Churn.xlsx', index=False)

In [28]:
#Creating VIEW vw_ChurnData

conn.execute("""
CREATE VIEW vw_ChurnData AS
SELECT * from prod_Churn where Customer_Status IN ('Churned','Stayed')""")

In [29]:
#Creating VIEW vw_JoinData

conn.execute("""
CREATE VIEW vw_JoinData AS
SELECT * from prod_Churn where Customer_Status = 'Joined'""")

In [34]:
vw_ChurnDataImport = pd.read_sql_query(
    "SELECT * FROM vw_ChurnData",
    conn)

In [37]:
vw_ChurnDataImport["Customer_Status"].unique()

array(['Stayed', 'Churned'], dtype=object)

In [ ]:
#Import data to excel
vw_ChurnDataImport.to_excel('vw_ChurnData.xlsx",
    index=False)

In [38]:
vw_JoinDataImport = pd.read_sql_query(
    "SELECT * FROM vw_JoinData",
    conn)

In [40]:
vw_JoinDataImport["Customer_Status"].unique()

array(['Joined'], dtype=object)

In [ ]:
#Import data to excel
vw_JoinDataImport.to_excel('vw_JoinData.xlsx",
    index=False)